apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: orderflow
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: orderflow
spec:
  clusterIP: None

  selector:
    app.kubernetes.io/name: redis

  ports:
    - name: redis
      port: 6379
      targetPort: redis
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: orderflow
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: orderflow
spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: redis

  ports:
    - name: redis
      port: 6379
      targetPort: redis
      protocol: TCP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: orderflow
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: orderflow
spec:
  serviceName: redis-headless
  replicas: 1

  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain

  selector:
    matchLabels:
      app.kubernetes.io/name: redis

  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/part-of: orderflow

    spec:
      terminationGracePeriodSeconds: 30

      containers:
        - name: redis
          image: redis:7-alpine
          imagePullPolicy: IfNotPresent

          command:
            - redis-server

          args:
            - --save
            - ""
            - --appendonly
            - "yes"
            - --appendfsync
            - everysec
            - --aof-use-rdb-preamble
            - "yes"
            - --dir
            - /data
            - --protected-mode
            - "no"

          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP

          startupProbe:
            exec:
              command:
                - redis-cli
                - ping
            periodSeconds: 2
            timeoutSeconds: 2
            failureThreshold: 30

          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            periodSeconds: 3
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi

          volumeMounts:
            - name: redis-data
              mountPath: /data

  volumeClaimTemplates:
    - metadata:
        name: redis-data
        labels:
          app.kubernetes.io/name: redis
          app.kubernetes.io/part-of: orderflow

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 1Gi